### ISSUE TITLE
No Method Map Error 

### ISSUE THREAD

**Issue by Jtread0000** [legacybass/Jeopardy#4]
Hey, Getting this error when attempting to Play game (after creating Categories of questions named "History") Have you seen this before?

TypeError: Object History has no method 'map'
    at...Jeopardy-master/Controllers/ApiController.js:238:29
    at callbacks (/Users/.../Desktop/Jeopardy-master/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/.../Desktop/Jeopardy-master/node_modules/express/lib/router/index.js:138:11)
    at pass (/Users/.../Desktop/Jeopardy-master/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/Users/.../Desktop/Jeopardy-master/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/Users/.../Desktop/Jeopardy-master/node_modules/express/lib/router/index.js:33:10)
    at next (/Users/.../Desktop/Jeopardy-master/node_modules/express/node_modules/connect/lib/proto.js:174:15)
    at next (/Users/.../Desktop/Jeopardy-master/node_modules/express/node_modules/connect/lib/proto.js:176:9)
    at Object.<anonymous> (/Users/.../Desktop/Jeopardy-master/node_modules/express/node_modules/connect/node_modules/express-session/index.js:433:7)

**Comment by legacybass** [comment]
No, I haven't seen that. I haven't looked at this project for some time, though, and have been meaning to get back to it. However, I don't know why it would be saying that History has no map method, since there isn't a variable named History. Maybe it's just how it's representing the object. Either way, I'll see if I can reproduce it when I get into finishing this project.
